version: '3.8'

services:
  notes-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver-dev;Database=NotesAppDev;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true;
      - JWT__SecretKey=development-secret-key-not-for-production-use-only-make-it-very-long
      - JWT__Issuer=NotesApp
      - JWT__Audience=NotesApp
      - JWT__ExpiryHours=24
      - Cors__AllowedOrigins__0=http://localhost:3000
      - Cors__AllowedOrigins__1=https://localhost:3000
      - Cors__AllowedOrigins__2=http://localhost:3001
    depends_on:
      - sqlserver-dev
    volumes:
      - .:/app
      - app_logs:/app/logs
    working_dir: /app
    networks:
      - notes-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["dotnet", "watch", "run", "--project", "NotesApp.csproj", "--urls", "http://+:80"]

  sqlserver-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data_dev:/var/opt/mssql
    networks:
      - notes-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123! -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  sqlserver_data_dev:
    driver: local
  app_logs:
    driver: local

networks:
  notes-network-dev:
    driver: bridge 