name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: 'Setup .NET 9'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: 'Restore dependencies'
      run: dotnet restore ./backend/NotesApp.csproj
    
    - name: 'Build project'
      run: dotnet build ./backend/NotesApp.csproj --configuration Release --no-restore
    
    - name: 'Publish project'
      run: dotnet publish ./backend/NotesApp.csproj --configuration Release --no-build --output ./backend/publish
    
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'collaborative-notes-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend/publish' 